name: ci
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: chainguard-images/actions/apko-publish@79f3e36e70469e4f6c278a226174d529d1d8cfc8
        with:
          tag: ghcr.io/microrun/host-toolchain:latest
      